<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RosesPGBalance_Library</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="C:\Users\Uriel\Music\Frameworks\RPGBAlance\Class1.cs" Link="Class1.cs" />
  </ItemGroup>

</Project>
